# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e87198fbf753dd708943dd199d8ac07d"
name = "Quantity Breaks"
application_url = "https://jm-quantity-breaks.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [ "https://jm-quantity-breaks.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
